version: "2.4"

volumes:
  elements_data:
  elements_shared:
  dave_data:
  emma_data:

services:
  elements:
    container_name: ${COMPOSE_PROJECT_NAME}_elements
    image: bitcoinstack/elements:0.18.1.9-alpine
    restart: unless-stopped
    command: [
      "-chain=liquid-regtest",
      "-validatepegin=1",
      "-upnp=0",
      "-server=1",
      "-txindex=1",
      "-onlynet=ipv4",
      "-dnsseed=0",
      "-dbcache=10",
      "-initialfreecoins=0",
      "-port=${ELEMENTS_PORT}",
      "-rpcport=${ELEMENTS_RPC_PORT}",
      "-rpcuser=${ELEMENTS_RPC_USER}",
      "-rpcpassword=${ELEMENTS_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=127.0.0.1",
      "-rpcbind=${ELEMENTS_HOST}",
      "-zmqpubrawtx=tcp://0.0.0.0:${ELEMENTS_ZMQ_TX_PORT}",
      "-zmqpubhashblock=tcp://0.0.0.0:${ELEMENTS_ZMQ_BLOCK_PORT}",
      "-mainchainrpchost=${BITCOIN_HOST}",
      "-mainchainrpcport=${BITCOIN_RPC_PORT}",
      "-mainchainrpcuser=${BITCOIN_RPC_USER}",
      "-mainchainrpcpassword=${BITCOIN_RPC_PASSWORD}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${ELEMENTS_HOST}
    ports:
      - "127.0.0.1:${ELEMENTS_RPC_PORT}:${ELEMENTS_RPC_PORT}"
    volumes:
      - elements_data:/home/elements/.elements
      - elements_shared:/opt/elements/bin

  dave:
    container_name: ${COMPOSE_PROJECT_NAME}_dave
    image: bitcoinstack/clightning:0.9.3-alpine
    restart: unless-stopped
    command: [
      "--alias=dave",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${DAVE_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    networks:
      bitcoinstacknet:
        aliases:
          - ${DAVE_HOST}
    volumes:
      - dave_data:/home/clightning/.lightning
      - elements_shared:/elements

  emma:
    container_name: ${COMPOSE_PROJECT_NAME}_emma
    image: bitcoinstack/clightning:0.9.3-alpine
    restart: unless-stopped
    command: [
      "--alias=emma",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${EMMA_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    networks:
      bitcoinstacknet:
        aliases:
          - ${EMMA_HOST}
    volumes:
      - emma_data:/home/clightning/.lightning
      - elements_shared:/elements