name: Docker

env:
  BUILD_TARGETS: linux/amd64,linux/arm64

on:
  push:
    branches: [ feat/actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Prepare builds
      id: prepare
      run: |
        docker manifest inspect bitcoinstack/lnd:test &>/dev/null || echo ::set-output name=lnd::test
        docker manifest inspect bitcoinstack/clightning:0.10.1-alpine &>/dev/null || echo ::set-output name=clightning::0.10.1-alpine

    - name: Build and push Clightning
      id: build-clightning
      if: ${{ steps.prepare.outputs.clightning }}
      uses: docker/build-push-action@v2
      with:
        context: ./clightning
        platforms: ${{ env.BUILD_TARGETS }}
        push: true
        tags: bitcoinstack/clightning:${{ steps.prepare.outputs.clightning }}

    - name: Build and push LND
      id: build-lnd
      if: ${{ steps.prepare.outputs.lnd }}
      uses: docker/build-push-action@v2
      with:
        context: ./lnd
        platforms: ${{ env.BUILD_TARGETS }}
        push: true
        tags: bitcoinstack/lnd:${{ steps.prepare.outputs.lnd }}