name: Docker

on:
  push:
    branches: [ feat/actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Prepare builds
      id: prepare
      run: |
        echo ${{ steps.qemu.outputs.platforms }}
        docker manifest inspect bitcoinstack/lnd:test &> /dev/null || echo ::set-output name=lnd::test
        docker manifest inspect bitcoinstack/clighnting:0.10.1-alpine &> /dev/null || echo ::set-output name=clightning::0.10.1-alpine

    - name: Build and push LND
      id: build-lnd
      if: ${{ steps.prepare.outputs.lnd }}
      uses: docker/build-push-action@v2
      with:
        context: ./lnd
        platforms: ${{ steps.qemu.outputs.platforms }}
        push: true
        tags: bitcoinstack/lnd:${{ steps.prepare.outputs.lnd }}